### PR TITLE
Semaintic-UI Dropdown - on

### PR DESCRIPTION
**Pull request by comerc**

### CODE REVIEW

**Comment by ManuelDeLeon** [comment]
You're doing it way harder than it needs to be:

https://github.com/ManuelDeLeon/phonebook/commit/c426d250f97a9e04185840179cec7d6ee99b5f65
https://github.com/ManuelDeLeon/phonebook/commit/8d7e938437ed03799e02b7e0f0d08ae36501faa3

**Comment by comerc** [comment]
Thanks, cool!

**Comment by comerc** [comment]
We have bug: "All Categories" > "New contact" > "Create contact" - not set value in categoryId.

**Comment by ManuelDeLeon** [comment]
Fixed

**Comment by ManuelDeLeon** [comment]
semantic blew up the previous events =/

**Pull request closed without merging**
